version: '3.9'
services:
  app:
    image: zhengtan2003/schedule
    environment:
      - PORT=3000
      - TZ=Asia/Shanghai
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=schedule123456
      - DATABASE_DATABASE=schedule
      - CLIENT_ROOT_PATH=./client
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - data:/app/server/data
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - mysql:/var/lib/mysql
    restart: always
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=schedule
      - MYSQL_ROOT_PASSWORD=schedule123456
    ports:
      - "7001:3306"

volumes:
  mysql:
  data:
